gatsbyBlog:
  component: '@serverless/tencent-website'
  inputs:
    code:
      src: ./public # Gatsby 生成的目录
      index: index.html
      error: index.html
    region: ap-beijing # 选择你希望部署的地区
    bucketName: my-bucket-gatsby-blog
